"use client";

import { createContext, useContext } from 'react';

export type DialogId =
    | 'customer-list'
    | 'add-customer'
    | 'customer-payment'
    | 'add-customer-payment'
    | 'customer-loyalty-points'
    | 'loyalty-settings'
    | 'add-loyalty-card'
    | 'add-loyalty-setting'
    | 'add-loyalty-points'
    | 'inventory'
    | 'add-product'
    | 'chart-of-accounts'
    | 'journal-entry'
    | 'view-journal'
    | 'new-account'
    | 'edit-account'
    | 'delete-account'
    | 'reconcile-account'
    | 'account-transfer'
    | 'create-invoice'
    | 'enter-cash-sale'
    | 'add-sales-user'
    | 'edit-sales-user'
    | 'delete-sales-user'
    | 'sales-users'
    | 'add-user-permission'
    | 'edit-user-permission'
    | 'delete-user-permission'
    | 'user-permissions'
    | 'business-setup'
    | 'create-purchase-order'
    | 'supplier-list'
    | 'add-supplier'
    | 'purchase-order-list'
    | 'view-purchase-order'
    | 'invoice-list'
    | 'accounts-payable'
    | 'enter-payments-of-accounts-payable'
    | 'enter-direct-payments'
    | 'enter-ap'
    | 'calendar-modal'
    | 'cash-fund-request'
    | 'bulk-upload-purchase-order'
    | 'purchase-history'
    | 'bulk-upload-accounts'
    | 'enter-payment'
    | 'view-transaction'
    | 'edit-transaction'
    | 'enter-payments'
    | 'receipts-deposits'
    | 'customer-balance'
    | 'backup-scheduler'
    | 'balance-sheet-report'
    | 'income-statement'
    | 'balance-sheet'
    | 'item-sales-report-dialog'
    | 'item-sales-report'
    | 'cash-flow-statement-dialog'
    | 'cash-flow-report'
    | 'trial-balance-dialog'
    | 'trial-balance-report'
    | 'consolidated-reports-dialog'
    | 'consolidated-report'
    | 'income-statement-analysis-dialog'
    | 'income-statement-analysis-report'
    | 'income-statement-report'
    | 'invoices-report-dialog'
    | 'invoices-report'
    | 'cash-advance-report-dialog'
    | 'cash-advance-report'
    | 'orders-report-dialog'
    | 'orders-report'
    | 'sales-invoice-payment-report-dialog'
    | 'sales-invoice-payment-report'
    | 'inventory-report-dialog'
    | 'inventory-report'
    | 'salesperson-report-dialog'
    | 'salesperson-report'
    | 'unpaid-accounts-report-dialog'
    | 'unpaid-accounts-report'
    | 'accounts-payable-report-dialog'
    | 'accounts-payable-report'
    | 'ap-payments-report-dialog'
    | 'ap-payments-report'
    | 'ar-aging-report-dialog'
    | 'ar-aging-report'
    | 'customers-report-dialog'
    | 'customers-report'
    | 'items-per-customer-report-dialog'
    | 'items-per-customer-report'
    | 'customer-sales-report-dialog'
    | 'customer-sales-report'
    | 'reconciliation-report-dialog'
    | 'reconciliation-report'
    | 'account-enquiry-report-dialog'
    | 'account-enquiry-report'
    | 'chart-of-accounts-report-dialog'
    | 'chart-of-accounts-report'
    | 'mileage-report-dialog'
    | 'mileage-report'
    | 'tax-report-dialog'
    | 'tax-report'
    | 'budget-report-dialog'
    | 'budget-report'
    | 'custom-report-dialog'
    | 'custom-report'
    | 'pos-sales-detail'
    | 'general-ledger-dialog'
    | 'general-ledger-report'
    | 'to-audit-report'
    | 'consignment-outright-report-dialog'
    | 'consignment-outright-report'
    | 'bank-settings'
    | 'add-bank-account'
    | 'edit-bank-account'
    | 'bank-history'
    | 'add-bank-transaction'
    | 'branch-list'
    | 'add-branch'
    | 'employee-directory'
    | 'add-employee'
    | 'edit-employee'
    | 'delete-employee'
    | 'customer-statement'
    | 'customer-ledger'
    | 'disbursement-dialog';

export interface DialogContextType {
    openDialogs: Record<string, boolean>;
    openDialog: (id: DialogId) => void;
    closeDialog: (id: DialogId) => void;
    getDialogData: (id: DialogId) => any;
    setDialogData: (id: DialogId, data: any) => void;
}

export const DialogContext = createContext<DialogContextType | undefined>(undefined);

export function useDialog() {
    const context = useContext(DialogContext);
    if (context === undefined) {
        throw new Error('useDialog must be used within a DialogProvider');
    }
    return context;
}
