import { Timestamp } from 'firebase/firestore';
import type { Transaction } from '@/types/transaction';

export const mockTransactions: Transaction[] = [
  {
    id: 'mock-1',
    seq: 1,
    ledger: 'General Ledger',
    transNo: 'TRN-001',
    code: 'GL001',
    accountNumber: '1001',
    date: Timestamp.fromDate(new Date('2023-10-01')),
    invoiceNumber: 'INV-001',
    particulars: 'Opening balance entry',
    debit: 10000.00,
    credit: 0.00,
    balance: 10000.00,
    checkAccountNumber: null,
    checkNumber: null,
    dateMatured: null,
    accountName: 'Cash Account',
    bankName: null,
    bankBranch: null,
    user: 'Admin',
    isCoincide: null,
    dailyClosing: null,
    approval: 'Approved',
    ftToLedger: null,
    ftToAccount: null,
    ssma_timestamp: Timestamp.now(),
  },
  {
    id: 'mock-2',
    seq: 2,
    ledger: 'General Ledger',
    transNo: 'TRN-002',
    code: 'GL002',
    accountNumber: '2001',
    date: Timestamp.fromDate(new Date('2023-10-02')),
    invoiceNumber: 'INV-002',
    particulars: 'Purchase of office supplies',
    debit: 0.00,
    credit: 2500.00,
    balance: 7500.00,
    checkAccountNumber: 'CHK-ACC-001',
    checkNumber: 'CHK-12345',
    dateMatured: Timestamp.fromDate(new Date('2023-10-15')),
    accountName: 'Office Supplies Expense',
    bankName: 'Bank of Example',
    bankBranch: 'Main Branch',
    user: 'User1',
    isCoincide: true,
    dailyClosing: 1,
    approval: 'Pending',
    ftToLedger: null,
    ftToAccount: null,
    ssma_timestamp: Timestamp.now(),
  },
  {
    id: 'mock-3',
    seq: 3,
    ledger: 'General Ledger',
    transNo: 'TRN-003',
    code: 'GL003',
    accountNumber: '3001',
    date: Timestamp.fromDate(new Date('2023-10-03')),
    invoiceNumber: 'INV-003',
    particulars: 'Sale of services',
    debit: 5000.00,
    credit: 0.00,
    balance: 12500.00,
    checkAccountNumber: null,
    checkNumber: null,
    dateMatured: null,
    accountName: 'Service Revenue',
    bankName: null,
    bankBranch: null,
    user: 'User2',
    isCoincide: false,
    dailyClosing: null,
    approval: 'Approved',
    ftToLedger: 'Ledger2',
    ftToAccount: 'Account2',
    ssma_timestamp: Timestamp.now(),
  },
  {
    id: 'mock-4',
    seq: 4,
    ledger: 'General Ledger',
    transNo: 'TRN-004',
    code: 'GL004',
    accountNumber: '1001',
    date: Timestamp.fromDate(new Date('2023-10-04')),
    invoiceNumber: 'INV-004',
    particulars: 'Bank deposit',
    debit: 3000.00,
    credit: 0.00,
    balance: 15500.00,
    checkAccountNumber: null,
    checkNumber: null,
    dateMatured: null,
    accountName: 'Cash Account',
    bankName: 'Bank of Example',
    bankBranch: 'Downtown Branch',
    user: 'Admin',
    isCoincide: null,
    dailyClosing: 2,
    approval: 'Approved',
    ftToLedger: null,
    ftToAccount: null,
    ssma_timestamp: Timestamp.now(),
  },
  {
    id: 'mock-5',
    seq: 5,
    ledger: 'General Ledger',
    transNo: 'TRN-005',
    code: 'GL005',
    accountNumber: '4001',
    date: Timestamp.fromDate(new Date('2023-10-05')),
    invoiceNumber: 'INV-005',
    particulars: 'Payment of utilities',
    debit: 0.00,
    credit: 800.00,
    balance: 14700.00,
    checkAccountNumber: 'CHK-ACC-002',
    checkNumber: 'CHK-67890',
    dateMatured: Timestamp.fromDate(new Date('2023-10-20')),
    accountName: 'Utilities Expense',
    bankName: 'Bank of Example',
    bankBranch: 'Main Branch',
    user: 'User3',
    isCoincide: true,
    dailyClosing: null,
    approval: 'Approved',
    ftToLedger: null,
    ftToAccount: null,
    ssma_timestamp: Timestamp.now(),
  },
];
