import type { Account } from '@/types/account';

export const mockAccounts: Account[] = [
  {
    id: 'mock-1',
    number: 1000,
    name: 'Cash on Hand',
    category: 'Assets',
    type: 'Asset',
    header: 'No',
    bank: 'No',
    balance: 50000.00,
  },
  {
    id: 'mock-2',
    number: 1100,
    name: 'Bank Account - BDO',
    category: 'Assets',
    type: 'Asset',
    header: 'No',
    bank: 'Yes',
    balance: 150000.00,
  },
  {
    id: 'mock-3',
    number: 1200,
    name: 'Accounts Receivable',
    category: 'Assets',
    type: 'Asset',
    header: 'No',
    bank: 'No',
    balance: 25000.00,
  },
  {
    id: 'mock-4',
    number: 2000,
    name: 'Accounts Payable',
    category: 'Liabilities',
    type: 'Liability',
    header: 'No',
    bank: 'No',
    balance: 30000.00,
  },
  {
    id: 'mock-5',
    number: 2100,
    name: 'Loans Payable',
    category: 'Liabilities',
    type: 'Liability',
    header: 'No',
    bank: 'No',
    balance: 100000.00,
  },
  {
    id: 'mock-6',
    number: 3000,
    name: 'Capital Stock',
    category: 'Equity',
    type: 'Equity',
    header: 'No',
    bank: 'No',
    balance: 200000.00,
  },
  {
    id: 'mock-7',
    number: 4000,
    name: 'Sales Revenue',
    category: 'Revenue',
    type: 'Income',
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-8',
    number: 5000,
    name: 'Cost of Goods Sold',
    category: 'Expenses',
    type: 'Expense',
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-9',
    number: 5100,
    name: 'Office Supplies Expense',
    category: 'Expenses',
    type: 'Expense',
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-10',
    number: 5200,
    name: 'Utilities Expense',
    category: 'Expenses',
    type: 'Expense',
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
];
