import type { Account } from '@/types/account';

export const mockAccounts: Account[] = [
  {
    id: 'mock-1',
    account_no: 1101,
    account_name: 'Cash on Hand',
    account_category: 'Assets',
    account_type: 'Asset',
    account_type_no: 1,
    header: 'No',
    bank: 'Yes',
    balance: 50000.00,
  },
  {
    id: 'mock-2',
    account_no: 1103,
    account_name: 'Cash in Bank',
    account_category: 'Assets',
    account_type: 'Asset',
    account_type_no: 1,
    header: 'No',
    bank: 'Yes',
    balance: 150000.00,
  },
  {
    id: 'mock-3',
    account_no: 1104,
    account_name: 'Accounts Receivable',
    account_category: 'Assets',
    account_type: 'Asset',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 25000.00,
  },
  {
    id: 'mock-4',
    account_no: 2101,
    account_name: 'Accounts Payable',
    account_category: 'Liabilities',
    account_type: 'Liability',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: -30000.00,
  },
  {
    id: 'mock-5',
    account_no: 2201,
    account_name: 'Bank Loan',
    account_category: 'Liabilities',
    account_type: 'Liability',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: -100000.00,
  },
  {
    id: 'mock-6',
    account_no: 3101,
    account_name: 'Owner\'s Capital',
    account_category: 'Equity',
    account_type: 'Equity',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: -200000.00,
  },
  {
    id: 'mock-7',
    account_no: 4101,
    account_name: 'Sales Revenue',
    account_category: 'Income',
    account_type: 'Income',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-8',
    account_no: 5101,
    account_name: 'Cost of Goods Sold',
    account_category: 'Cost of Sales',
    account_type: 'Expense',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-9',
    account_no: 6105,
    account_name: 'Office Supplies Expense',
    account_category: 'Expenses',
    account_type: 'Expense',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-10',
    account_no: 6104,
    account_name: 'Utilities Expense',
    account_category: 'Expenses',
    account_type: 'Expense',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
];
