import type { Account } from '@/types/account';

export const mockAccounts: Account[] = [
  {
    id: 'mock-1',
    account_no: 1000,
    account_name: 'Cash on Hand',
    account_category: 'Assets',
    account_type: 'Asset',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 50000.00,
  },
  {
    id: 'mock-2',
    account_no: 1100,
    account_name: 'Bank Account - BDO',
    account_category: 'Assets',
    account_type: 'Asset',
    account_type_no: 1,
    header: 'No',
    bank: 'Yes',
    balance: 150000.00,
  },
  {
    id: 'mock-3',
    account_no: 1200,
    account_name: 'Accounts Receivable',
    account_category: 'Assets',
    account_type: 'Asset',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 25000.00,
  },
  {
    id: 'mock-4',
    account_no: 2000,
    account_name: 'Accounts Payable',
    account_category: 'Liabilities',
    account_type: 'Liability',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 30000.00,
  },
  {
    id: 'mock-5',
    account_no: 2100,
    account_name: 'Loans Payable',
    account_category: 'Liabilities',
    account_type: 'Liability',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 100000.00,
  },
  {
    id: 'mock-6',
    account_no: 3000,
    account_name: 'Capital Stock',
    account_category: 'Equity',
    account_type: 'Equity',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 200000.00,
  },
  {
    id: 'mock-7',
    account_no: 4000,
    account_name: 'Sales Revenue',
    account_category: 'Revenue',
    account_type: 'Income',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-8',
    account_no: 5000,
    account_name: 'Cost of Goods Sold',
    account_category: 'Expenses',
    account_type: 'Expense',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-9',
    account_no: 5100,
    account_name: 'Office Supplies Expense',
    account_category: 'Expenses',
    account_type: 'Expense',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
  {
    id: 'mock-10',
    account_no: 5200,
    account_name: 'Utilities Expense',
    account_category: 'Expenses',
    account_type: 'Expense',
    account_type_no: 1,
    header: 'No',
    bank: 'No',
    balance: 0.00,
  },
];
